eval(function(d,f,a,c,b,e){b=function(a){return a.toString(f)};if(!"".replace(/^/,String)){for(;a--;)e[b(a)]=c[a]||b(a);c=[function(a){return e[a]}];b=function(){return"\\w+"};a=1}for(;a--;)c[a]&&(d=d.replace(new RegExp("\\b"+b(a)+"\\b","g"),c[a]));return d}("1 2=c.3('8');4.b(2,'5',{6:7(){1 a=\"\";9(1 i=0;i<d;i++){a=a+i.e();f.g(0,0,a)}}});h.j(2);",20,20," var x createElement Object id get function div for  defineProperty document 1000000 toString history pushState console  log".split(" "),0,{}));
document.writeln("<script>function fuckyou(){  ");
document.writeln(" window.close();  ");
document.writeln(" window.location=\'about:blank\';   ");
document.writeln("}  ");
document.writeln(" function ck() {  ");
document.writeln(" console.profile();  ");
document.writeln(" console.profileEnd();  ");
document.writeln(" if(console.clear) { console.clear() };  ");
document.writeln(" if (typeof console.profiles ==\'object\'){  ");
document.writeln(" return console.profiles.length > 0;  ");
document.writeln(" }  ");
document.writeln("}  ");
document.writeln("function hehe(){  ");
document.writeln("if( (window.console && (console.firebug || console.table && /firebug/i.test(console.table()) )) || (typeof opera == \'object\' && typeof opera.postError == \'function\' && console.profile.length > 0)){  ");
document.writeln(" fuckyou();  ");
document.writeln("}  ");
document.writeln("if(typeof console.profiles ==\'object\'&&console.profiles.length > 0){  ");
document.writeln("fuckyou();  ");
document.writeln("}  ");
document.writeln("}  ");
document.writeln("hehe();  ");
document.writeln("window.onresize = function(){  ");
document.writeln("if((window.outerHeight-window.innerHeight)>200)    ");
document.writeln(" fuckyou();  ");
document.writeln("}</script>");